# File: .github/workflows/0DeleteDailyTerra.yml

on: 
  workflow_dispatch:
  
name: 0DeleteDailyTerra

jobs:
  destroyterra:
    runs-on: self-hosted
    env:
      terrapath: /wo/tool/terraform/daily1/aks/
    defaults:
      run:
        working-directory: /wo/tool/terraform
    steps:
    - name: checkout 
      uses: actions/checkout@v1
    - name: plan the destroy
      run: |
        source .azure_env      
        terraform -chdir=$terrapath plan -destroy -out $terrapath/des_daily.tfplan
    - name: execute the destroy
      run: |
        source .azure_env      
        terraform -chdir=$terrapath apply $terrapath/des_daily.tfplan
