# File: .github/workflows/test.yml

on: 
  workflow_dispatch:
  workflow_run:
    workflows: [StartJSEveryDay]
    types:
      - completed
      
name: dailyterra

jobs:
  runterra:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      terrapath: /wo/tool/terraform/daily1/aks/
    defaults:
      run:
        working-directory: /wo/tool/terraform
    steps:
    - name: checkout 
      uses: actions/checkout@v1
    - name: plan the job
      run: |
        source .azure_env
        run_terraform $terrapath
#        terraform -chdir=$terrapath plan -out $terrapath/daily.tfplan
#    - name: execute the job
#      run: |
#        source .azure_env      
#        terraform -chdir=$terrapath apply $terrapath/daily.tfplan
  
    
