# File: .github/workflows/test.yml

on: 
  workflow_dispatch:
  
name: dailyterra

jobs:
  runterra:
    runs-on: self-hosted
    env:
      terrapath: /wo/tool/terraform/daily1/aks/
    defaults:
      run:
        working-directory: /wo/tool/terraform
    steps:
    - name: checkout 
      uses: actions/checkout@v1
    - name: plan the job
      run: |
        pwd
        source .azure_env
        echo $ARM_SUBSCRIPTION_ID
#    - name: plan the job
#      run: terraform -chdir=$terrapath plan -out $terrapath/daily.tfplan
#    - name: execute the job
#      run: terraform -chdir=$terrapath apply $terrapath/daily.tfplan
  
    
