# File: .github/workflows/startJS.yml

on: 
  schedule:
    - cron: '30 23 * * *'
  workflow_dispatch:
    
name: StartJSEveryDay


jobs:
  startVM:
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Checkout
      uses: actions/checkout@v1
    - name: Azure CLI script file
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az vm start -g NEWDAILY -n sh-daily-work
  sleepwait:
    needs: startVM
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: sleep
      run: sleep 60
    
