# File: .github/workflows/test.yml

on: 
  workflow_dispatch:
  
name: test

jobs:
  testcommand:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: give value
      run: cat=$(echo dog)
    - name: get value
      run: echo $cat
    - name: get path
      run: pwd
    - name: go path
      run: cd /root/ingress-nginx
    - name: get path
      run: pwd
    
